name: ${project.parent.name}
version: ${project.parent.version}
author: NEZNAMY
main: me.neznamy.tab.platforms.bukkit.Main
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, UltraPermissions, LuckPerms, Essentials, LibsDisguises, ProtocolSupport, ViaVersion]
website: "https://github.com/NEZNAMY/TAB"
description: ${project.parent.description}
commands:
  tab:
